## Q1. Pandas version

What version of Pandas did you install?

In [64]:
import pandas as pd
pd.__version__

'3.0.6'

Answer: 3.0.6

## Getting the data

In [65]:
!wget -nc https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

File ‘car_fuel_efficiency_2026.csv’ already there; not retrieving.

## Q2. Records count

How many records are in the dataset?

In [136]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.shape

(10000, 11)

Answer: 10000  
We could also just run `df.shape[0]` but I wanted to see the number of series (columns) as well.

## Q3. Fuel types

How many fuel types are presented in the dataset?

In [67]:
df.head()
# I want to see the series names. I could use `df.columns`, but I want to see some sample values from all series.

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [68]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

Answer: 3  
We could also run `df['fuel_type'].unique().shape[0]` or `len(df['fuel_type'].unique().tolist())` to get just the answer, but I wanted to see those values.

## Q4. Missing values

How many columns in the dataset have missing values?

There are a few ways to get this information.

In [36]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [43]:
df.isna().any()

model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors              False
engine_displacement    False
num_cylinders          False
horsepower              True
vehicle_weight         False
acceleration            True
fuel_efficiency_mpg    False
dtype: bool

In [69]:
df.columns[df.isna().any()]

Index(['horsepower', 'acceleration'], dtype='str')

In [70]:
len(df.columns[df.isna().any()].tolist())

2

Answer: 2

## Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [54]:
cars_from_asia = df[df['origin'] == 'Asia']
cars_from_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [58]:
max_fuel_efficiency_of_cars_from_asia = cars_from_asia['fuel_efficiency_mpg'].max()
max_fuel_efficiency_of_cars_from_asia

np.float64(41.2)

In [71]:
# One liner for the above two lines of code:
df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

np.float64(41.2)

Answer: 41.2

## Q6. Median value of horsepower

1. Find the median value of the horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.

Has it changed?

In [133]:
# 1. Find the median value of the horsepower column in the dataset.
df['horsepower'].median()

np.float64(252.0)

In [134]:
# 2. Next, calculate the most frequent value of the same horsepower column.
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [137]:
# 3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
# I want to see some rows where horsepower is NaN so that I can later verify that I have filled them with the most frequent value (mode).
df[df['horsepower'].isna()].head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
12,1983,USA,Diesel,Front-wheel drive,3,2370,7,NaN,4390,20.7,30.4
32,1978,USA,Gasoline,Rear-wheel drive,3,2080,6,NaN,4350,16.8,24.1
39,1994,Asia,Gasoline,Front-wheel drive,3,2390,6,NaN,4300,18.2,33.5
46,1983,Europe,Gasoline,Rear-wheel drive,4,2130,6,NaN,4360,20.9,29.7

In [96]:
# I want to know how to locate just one of those rows.
df.iloc[10,:]

model_year                        1978
origin                            Asia
fuel_type                     Gasoline
drivetrain             All-wheel drive
num_doors                            3
engine_displacement               2410
num_cylinders                        6
horsepower                         NaN
vehicle_weight                    4420
acceleration                      19.5
fuel_efficiency_mpg               26.8
Name: 10, dtype: object

In [97]:
df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)

/tmp/ipykernel_24670/1392585663.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [98]:
df.iloc[10,:]

model_year                        1978
origin                            Asia
fuel_type                     Gasoline
drivetrain             All-wheel drive
num_doors                            3
engine_displacement               2410
num_cylinders                        6
horsepower                         NaN
vehicle_weight                    4420
acceleration                      19.5
fuel_efficiency_mpg               26.8
Name: 10, dtype: object

In [ ]:
# I am keeping the error above in the notebook because I am sure that I will have to deal with this issue again in the future. I want to 
# document it and understand it better.
# The command `df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)` failed because Copy-on-Write (CoW) is now enabled 
# by default in pandas. 
# Under these rules, modifying a single column extracted from a DataFrame using an inplace=True method is treated as a chained assignment 
# and is explicitly blocked to prevent accidental data corruption.

In [99]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [100]:
df.iloc[10,:]

model_year                        1978
origin                            Asia
fuel_type                     Gasoline
drivetrain             All-wheel drive
num_doors                            3
engine_displacement               2410
num_cylinders                        6
horsepower                       252.0
vehicle_weight                    4420
acceleration                      19.5
fuel_efficiency_mpg               26.8
Name: 10, dtype: object

In [101]:
df[df['horsepower'].isna()].head()

Empty DataFrame
Columns: [model_year, origin, fuel_type, drivetrain, num_doors, engine_displacement, num_cylinders, horsepower, vehicle_weight, acceleration, fuel_efficiency_mpg]
Index: []

In [ ]:
# Aha! It worked. But let's learn more:  
# There's another way of doing it: df.fillna({'horsepower': df['horsepower'].mode()[0]}, inplace=True)
# The advantage of this last method is that you can fill multiple columns with different values in one go, because we're using a dictionary. 
# For example, if you wanted to fill 'horsepower' with its mode and 'weight' with its median, you could do:
# df.fillna({'horsepower': df['horsepower'].mode()[0], 'weight': df['weight'].median()}, inplace=True)

In [ ]:
# 4. Now, calculate the median value of horsepower once again.
df['horsepower'].median()

np.float64(252.0)

Answer: Yes, it decreased.

## Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
9. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

In [108]:
# 1. All the cars from Asia
all_the_cars_from_asia = df[df['origin'] == 'Asia']
all_the_cars_from_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [109]:
# 2. Select only columns vehicle_weight and model_year
selected_columns = all_the_cars_from_asia[['vehicle_weight', 'model_year']]
selected_columns.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

In [110]:
# 3. Select the first 7 values
first_seven_values = selected_columns.head(7)
first_seven_values

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [119]:
# 4. Get the underlying NumPy array. Let's call it X.
# IntelliSense (the autocomplete of VS Code) suggested to use `X = first_seven_values.values`
# But when I went to the official documentation of Pandas https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.values.html, 
# it shows a warning that recommends to use `to_numpy()` instead of `values`. So I will use that instead.
X = first_seven_values.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [122]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
# We're dealing with a Numpy object, so we have to look in the Numpy documentation.
# To transpose a matrix, we can use the `transpose()` method or the `.T` attribute. See https://numpy.org/devdocs/reference/generated/numpy.ndarray.T.html
# And for the matrix-matrix multiplication, we can use the `matmul()` method or the `@` operator.
# See https://numpy.org/doc/stable/reference/generated/numpy.matmul.html.
# It's interesting that it uses the `@` operator because Pandas also does as per https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transpose.html
# But why? It's because both rely on standard Python functionality introduced in PEP 465, which added the dedicated infix 
# operator @ to the Python language itself.
# Both libraries implement Python’s native __matmul__ special method. This creates a unified experience across the entire Python data science ecosystem.
# See https://peps.python.org/pep-0465/
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [117]:
# 6. Invert XTX.
# We're dealing with a Numpy object, so we have to look in the Numpy documentation for the method to invert a matrix.
# This https://numpy.org/doc/stable/reference/generated/numpy.invert.html#numpy.invert is NOT the correct documentation 
# because it is for inverting bits, not matrices. It calculates the bitwise "NOT" operation on the integers or booleans of the input array, element-wise.
# But https://numpy.org/devdocs/reference/generated/numpy.linalg.inv.html computes the multiplicative inverse of a square matrix. 
# It is the correct documentation for our case.
import numpy as np
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [125]:
# What if we were still dealing with a Pandas DataFrame instead of a Numpy array? How would we invert it?
# There is no method in Pandas to invert a DataFrame.
# Do NOT use the `pow()` method to invert a DataFrame by using the power of -1. It is not the correct method to do that. 
# See https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pow.html
# It would perform element-wise exponentiation, not matrix inversion.

In [127]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [128]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [132]:
# 9. What's the sum of all the elements of the result?
w.sum().round(3)

np.float64(0.369)

Answer: 0.369